### ISSUE TITLE
不支持支付宝小程序吗？打开即报错 -_-!

### ISSUE THREAD

**Issue by ZhongMingKun** [codercup/unibest#10]
Node版本: v20.9.0
pnpm版本: 8.15.4
运行设备: MacbookPro M1
系统版本: MacOS Sonoma 14.2.1
支付宝小程序开发者工具 3.8.11

![image](https://github.com/codercup/unibest/assets/33282718/de8b08d6-dfd4-44a6-bf2f-9396e3d5075a)

**Comment by codercup** [comment]
你用的是哪个模板，试试 pnm create unibest xxx -t base

**Comment by codercup** [comment]
另外，目前没有时间研究支付宝小程序，欢迎PR

**Comment by ZhongMingKun** [comment]
小程序开发工具**编译配置**中的**转ES5编译配置（新）**设置一下就可以了
![image](https://github.com/codercup/unibest/assets/33282718/da512440-24f0-4f5a-a035-d18a63e68cd3)

**Comment by codercup** [comment]
赞，感谢~
