### ISSUE TITLE
win的环境不可以吗？npm i 报错【推荐使用pnpm】

### ISSUE THREAD

**Issue by liuHongyang0207** [codercup/unibest#101]
运行npm i 报错
![错误](https://github.com/codercup/unibest/assets/108056008/1686e66e-1ff8-44d8-9eb8-5bfaa360ecad)

**Comment by JinliangYan** [comment]
- 执行 pnpm create unibest 创建项目

- 执行 pnpm i 安装依赖

- 执行 pnpm dev 运行 H5

**Comment by codercup** [comment]
对，试试 pnpm

**Comment by zhoutengshen** [comment]
构建服务器上，开发管不到，运维不给安装pnpm
