### ISSUE TITLE
@/utils/index 代码中建议

### ISSUE THREAD

**Issue by ckbabby** [codercup/unibest#102]
# Bug report（问题描述）
export const getUrlObj = (url: string) => {
  const [path, queryStr] = url.split('?')
  console.log(path, queryStr)

  const query: Record<string, string> = {}
  queryStr.split('&').forEach((item) => {
    const [key, value] = item.split('=')
    console.log(key, value)
    query[key] = ensureDecodeURIComponent(value) // 这里需要统一 decodeURIComponent 一下，可以兼容h5和微信y
  })
  return { path, query }
}
这里是否应该判断queryStr 是否为undefine 情况
please write your issue description here

## System Info

`npx envinfo --system --npmPackages vue --binaries --browsers`

执行上面命令，将结果贴下面

**Comment by codercup** [comment]
确实是，3q

**Comment by codercup** [comment]
已经处理。done
