### ISSUE TITLE
queryStr 可能为 undefined

### ISSUE THREAD

**Issue by xiyueyezibile** [codercup/unibest#114]
# Bug report（问题描述）

一个通用方法小问题

## Screenshot or Gif（截图或动态图）

![c146a5ea6f4f7035735e575003444ef8](https://github.com/codercup/unibest/assets/116241580/87fafa43-bfe0-4f55-a367-0b82e304d742)

## minimal reproduction（最小可还原代码）

// layout/default.vue

watch(
  () => currRoute(),
  (newVal) => {
    console.log(newVal)
  },
)

## System Info

`npx envinfo --system --npmPackages vue --binaries --browsers`

执行上面命令，将结果贴下面

**Comment by codercup** [comment]
感谢PR。已经修复
