### ISSUE TITLE
不知是wd组件的问题还是项目Unocss配置问题

### ISSUE THREAD

**Issue by vue-rookie** [codercup/unibest#122]
拉取main分支代码，wd-button加上class预设不起作用
![image](https://github.com/codercup/unibest/assets/168452915/6fa621cd-d5fa-4fc6-a701-79b3bde44496)

**Comment by codercup** [comment]
class 改为 custom-class, 你看看wot的官网有些

**Comment by vue-rookie** [comment]
ok.thanks
