### ISSUE TITLE
小程序真机调试在ios设备上会出现白屏

### ISSUE THREAD

**Issue by huanhuanismonito** [codercup/unibest#149]
#拉取base分支二开后，真机调试时安卓设备正常，ios上除原生tabbar和navbar以为页面都是白屏，调试过多个设备都是一样。然后重新拉取分支直接真机调试也是这个样子

白屏效果
![62d4ee71-0f61-413f-9707-e8c7172c314d](https://github.com/user-attachments/assets/82a64da9-4e0c-4a40-bb87-0bccfb9e87eb)

报错信息
![b771f8a1-84df-4e07-b293-1af6b5b33ac6](https://github.com/user-attachments/assets/3ab4e995-e07c-405a-b95c-4bd9b98987c1)

看了报错信息好像app.jsz找不到，调试发现在ios设备上app.vue当中的代码都没有执行。希望能够得到解答

**Comment by doxidai** [comment]
大佬你解决了么？

**Comment by arlindar1030** [comment]
我的也是
