### ISSUE TITLE
使用 unocss 中的 @apply ，在h5端会把rem转换为rpx

### ISSUE THREAD

**Issue by webarn** [codercup/unibest#16]
<img width="471" alt="image" src="https://github.com/codercup/unibest/assets/23495159/a95e75b6-a67a-4506-bb2b-824c9c3947a1">

**Comment by codercup** [comment]
<img width="631" alt="image" src="https://github.com/codercup/unibest/assets/65991901/93ce7980-d6aa-4c1b-8381-58c33740c84a">

**Comment by codercup** [comment]
<img width="656" alt="image" src="https://github.com/codercup/unibest/assets/65991901/a612e244-426c-4e8a-b103-2cd6052485bc">
