### ISSUE TITLE
有js版本吗？ts不习惯用，各种类型限制太麻烦，并且各种提示报错

### ISSUE THREAD

**Issue by sylarcui** [codercup/unibest#17]
![image](https://github.com/codercup/unibest/assets/4715714/827aa366-9cb8-4d5f-aa1a-779e50be135b)

**Comment by qazwsx9288** [comment]
这个项目的环境搭建实际上大部分是为了TS而做的。实在觉得类型体操很麻烦的话，可以写any script，不影响。特别是小团队甚至个人开发，TS确实必要性不大。

**Comment by github-cherry** [comment]
我也用不惯ts😂

**Comment by eamd-wq** [comment]
[钳子] [钳子]

**Comment by codercup** [comment]
兄弟们已经有js版了呀~

**Comment by codercup** [comment]
请看官网哈~ https://codercup.github.io/unibest-docs/guide/installation
![image](https://github.com/codercup/unibest/assets/65991901/af2a963b-3382-4cb0-a81e-6c4850241e78)

**Comment by echofly** [comment]
都4202年了，还不用ts？

**Comment by codercup** [comment]
推荐大家还是使用base模板吧，这个模板更新最积极。其他模板基本都是基于它更新的。
另外，base模板也支持编写 js，所以js模板可以不需要了。
