### ISSUE TITLE
Unbalanced delimiter found in string

### ISSUE THREAD

**Issue by dhanweb** [codercup/unibest#19]
```
// #ifdef VUE3
// #ifdef APP-PLUS
global = {}
// #endif
// #endif
// #ifndef APP-NVUE
import {Canvas, setCanvasCreator, dispatch} from './canvas';
import {wrapTouch, convertTouchesToArray, devicePixelRatio ,sleep, canIUseCanvas2d, getRect} from './utils';
// #endif
// #ifdef APP-NVUE
import { base64ToPath, sleep } from './utils';
import {Echarts} from './nvue'
// #endif
const charts = {}
const echartsObj = {}
```
uniapp条件编译表达式和格式化冲突了，编译就会报错` Unbalanced delimiter found in string`
这其中一部分是我在插件市场下载的echarts组件的多端兼容的代码，新建个vue文件，粘贴这段代码，保存格式化之后条件编译语句就会发现错乱了。
目前我是一个一个手动改正的，有什么好的解决方案吗。

**Comment by codercup** [comment]
> ```
> // #ifdef VUE3
> // #ifdef APP-PLUS
> global = {}
> // #endif
> // #endif
> // #ifndef APP-NVUE
> import {Canvas, setCanvasCreator, dispatch} from './canvas';
> import {wrapTouch, convertTouchesToArray, devicePixelRatio ,sleep, canIUseCanvas2d, getRect} from './utils';
> // #endif
> // #ifdef APP-NVUE
> import { base64ToPath, sleep } from './utils';
> import {Echarts} from './nvue'
> // #endif
> const charts = {}
> const echartsObj = {}
> ```
> 
> uniapp条件编译表达式和格式化冲突了，编译就会报错` Unbalanced delimiter found in string` 这其中一部分是我在插件市场下载的echarts组件的多端兼容的代码，新建个vue文件，粘贴这段代码，保存格式化之后条件编译语句就会发现错乱了。 目前我是一个一个手动改正的，有什么好的解决方案吗。

方便提供原始代码块吗？我们本地复现一下，方便修复

**Comment by dhanweb** [comment]
[l-echart.zip](https://github.com/codercup/unibest/files/14662925/l-echart.zip)
这个是插件市场下载的[echarts组件](https://ext.dcloud.net.cn/plugin?id=4899)的其中一个文件，包括script标签内和style标签内的的格式化问题，我都是在这个文件发现的。
还有个比较复杂的，条件编译下可能会写多个return，这样后面的return都会爆红线，例如这个文件的 canvasToTempFilePath 方法。

**Comment by codercup** [comment]
目前已经有一个 ucharts 的 unibest 模板，获取能帮到你。

**Comment by dhanweb** [comment]
> 目前已经有一个 ucharts 的 unibest 模板，获取能帮到你。

好的，非常感谢
