### ISSUE TITLE
uview-ui

### ISSUE THREAD

**Issue by liubo7763131** [codercup/unibest#22]
# Feature request（新功能建议）
什么时候能支持uview-ui 组件库

**Comment by codercup** [comment]
现在就使用 uview 系的组件库啊。uView 是 vue2的产品，现在 vue3 对应的是 uveiw-plus 和 uv-ui. 目前选择了 uv-ui。
后续可能考虑换成 vue3 + ts 的 wot-design-uni .  https://wot-design-uni.gitee.io/

**Comment by codercup** [comment]
另外，如果需要，可以自己替换组件库。
