### ISSUE TITLE
使用uni-ui库中的uni-popup, 代码使用的官方提供的demo，报错

### ISSUE THREAD

**Issue by webarn** [codercup/unibest#28]
```vue
<route lang="json5">
{
  layout: 'demo',
  style: { navigationBarTitleText: 'UniUI 使用' },
}
</route>

<template>
  <view>
    <button @click="open">打开弹窗</button>
    <uni-popup ref="popup" type="bottom" border-radius="10px 10px 0 0"
      >底部弹出 Popup 自定义圆角</uni-popup
    >
  </view>
</template>
<script>
export default {
  methods: {
    open() {
      // 通过组件定义的ref调用uni-popup方法 ,如果传入参数 ，type 属性将失效 ，仅支持 ['top','left','bottom','right','center']
      this.$refs.popup.open('top')
    },
  },
}
</script>

```

<img width="646" alt="image" src="https://github.com/codercup/unibest/assets/23495159/767aae6e-82fb-44dc-a958-04fc3cd9d93b">

问题2：
http://localhost:9000/#/pages/demo/route-interceptor/login-model?name=feige&age=30
这个页面也报错，
<img width="641" alt="image" src="https://github.com/codercup/unibest/assets/23495159/a3e98f0b-9ecd-4c0b-9496-b42cbc43fc11">

上面代码都是执行 `pnpm create unibest my-project -t demo`后得到的代码，无修改

**Comment by webarn** [comment]
uni-drawer也报错，和上面的错误一样

**Comment by codercup** [comment]
vue3 里面没有 this, 你需要改造下代码了，uni-ui 里面的文档是针对 vue2的。

**Comment by codercup** [comment]
推荐使用 vue3+setup 语法

<script lang="ts" setup>
const popup = ref()
const open = () => {
  popup.value?.open()
}
</script>

**Comment by codercup** [comment]
![Uploading image.png…]()

**Comment by codercup** [comment]
![image](https://github.com/codercup/unibest/assets/65991901/7a77583d-0e59-41f7-a0ce-2aea43078c0f)

**Comment by webarn** [comment]
@codercup 找到问题了，如果使用 `http://localhost:9000/` 必现，如果使用ip就正常使用。不知道是什么原因
