### ISSUE TITLE
使用vscode编辑，更改代码后安卓热更新内容不显示

### ISSUE THREAD

**Issue by wyq0201** [codercup/unibest#29]
在vscode编辑代码，保存，显示差量编译，hbuilder提示当前文件刷新成功。可是手机页面内容白屏了，tabbar还可以显示，可以点击，首页白屏关于页面内容显示正常。重新运行才可以正常显示
![1711174512608](https://github.com/codercup/unibest/assets/15724790/d7d64802-b12c-4286-a488-4dbedaaeaf71)
![1711174444529](https://github.com/codercup/unibest/assets/15724790/52b2333d-640e-473d-bd6a-99bf407fbf38)
![cbee888fad30e2a1a843a7619080f1a](https://github.com/codercup/unibest/assets/15724790/b4d1bd17-1144-4998-b0d5-f7734f90f115)
另外，群码过期了，麻烦更新一下

**Comment by wyq0201** [comment]
vscode控制台有个错，不知道是否和这个有关系
![1711177328020](https://github.com/codercup/unibest/assets/15724790/df2c26e4-7865-41e0-a460-2bd7e819cd5f)

**Comment by wyq0201** [comment]
> vscode控制台有个错，不知道是否和这个有关系 ![1711177328020](https://private-user-images.githubusercontent.com/15724790/316223928-df2c26e4-7865-41e0-a460-2bd7e819cd5f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODQ4ODMsIm5iZiI6MTcxMTE4NDU4MywicGF0aCI6Ii8xNTcyNDc5MC8zMTYyMjM5MjgtZGYyYzI2ZTQtNzg2NS00MWUwLWE0NjAtMmJkN2U4MTljZDVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA5MDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMmRlMjAyMDkwZDM2ZjU2N2Y5ZDA0YzBkZGE1OGZkNWYzNjA0OWFkYzEzNzlkZTFiZWEwNmVhYTY2ODE3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f4cJcFyAR1v-rR4-1oE3htk4XDj10G1btNonTjbwD-M)

这个报错的问题解决了

经测试，使用pnpm dev:app，然后用hbuilder导入运行，在vscode中修改，页面内容还是会白屏（真机和模拟器都一样）。
使用pnpm dev:mp，微信开发者工具导入，在vscode中修改可以热更新

hbuilder x是最新版3.99

**Comment by wyq0201** [comment]
使用pnpm dev:app-android可以实现热更新，iso没测试

**Comment by Nokecy** [comment]
我这边测试也是会白屏

**Comment by Coding-Journey-Studio** [comment]
> 使用pnpm dev:app-android可以实现热更新，iso没测试

android 也不行，必须重启应用才可以。。用的mumu模拟器
