### ISSUE TITLE
控制台提示Sourcemap for。。。。。。points to missing source files​

### ISSUE THREAD

**Issue by ZhangMinghi** [codercup/unibest#32]
![image](https://github.com/codercup/unibest/assets/45185657/09f35445-23a5-40e9-8599-0a9b4a3b2d81)
工程创建方式：pnpm create unibest my-project -t i18n
node版本：20.11.1
pnpm版本：8.15.5

**Comment by lz-freedom** [comment]
俺也一样

<img width="1793" alt="image" src="https://github.com/codercup/unibest/assets/32818030/da988112-c2ce-435e-9abd-79b000a1ce7c">

**Comment by shuTwT** [comment]
更新下vite版本就不弹了

**Comment by codercup** [comment]
> 更新下vite版本就不弹了

方便说下具体哪个vite版本吗？

**Comment by shuTwT** [comment]
> > 更新下vite版本就不弹了
> 
> 方便说下具体哪个vite版本吗？

我发现貌似4.4.0+不会弹，我目前用的是4.5.3

**Comment by lz-freedom** [comment]
4.0.3升级到4.5.3也不弹了，🙏
