### ISSUE TITLE
运行时会崩掉

### ISSUE THREAD

**Issue by gaao** [codercup/unibest#34]
# Bug report（问题描述）

运行pnpm run时会崩掉

## Steps to reproduce（问题复现步骤）

1. 当我本地终端运行项目pnpm dev:mp-weixin，此时没有问题
2. 如果我修改了项目文件保存后则会有几率项目停止运行，如下
```code 
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///D:/GXG/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:4246:10)
    at NodeFsHandler._boundHandleError (file:///D:/GXG/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:2720:43)
    at ReaddirpStream.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'D:\\DumpStack.log.tmp'
}
```

## System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.93 GB / 15.83 GB
  Binaries:
    Node: 21.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vue: 3.2.47 => 3.2.47

**Comment by gaao** [comment]
找到了一个解决方案，vitehttps://github.com/dcloudio/uni-app/issues/3603#issuecomment-1840415146，不过我试了第一种方法还是不行，第二种升级了vite到4.5.3后会有其他提示，不过运行不会崩了

**Comment by codercup** [comment]
目前我是这样写的，群友说一上午运行都没问题：
<img width="659" alt="image" src="https://github.com/codercup/unibest/assets/65991901/2d5f8b3a-fa49-4a3f-b87c-409d1285cf0e">
你说的第二种我没试过，昨天升级版本，vite版本，使用的是 "vite": "4.3.5"（你的是 4.5.3)

**Comment by codercup** [comment]
> 找到了一个同样问题，vitehttps://github.com/[dcloudio/uni-app/issues/3603](https://github.com/dcloudio/uni-app/issues/3603)#issuecomment-1840415146，不过我试了第一种方法还是不行，第二种升级了vite到4.5.3后会有其他提示，不过运行不会崩了

嗯，感谢提供链接，很有帮助。
