### ISSUE TITLE
请问后期考虑出一个没有ts的版本吗 

### ISSUE THREAD

**Issue by kangaroo711** [codercup/unibest#4]

**Comment by CodewordLiang** [comment]
你可以考虑anyscript

**Comment by codercup** [comment]
没有考虑js版，ts 是必须的哈~~

**Comment by gitboyzcf** [comment]
没有ts版的uni-app模板  模板简单易用  https://github.com/gitboyzcf/uni-preset-vue3-vite

**Comment by codercup** [comment]
base模板可以写js












飞鸽传书
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月17日(周三) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [codercup/unibest] 请问后期考虑出一个没有ts的版本吗  (Issue #4)




 
没有ts版的uni-app模板  模板简单易用  https://github.com/gitboyzcf/uni-preset-vue3-vite
