### ISSUE TITLE
请问组件支持用tsx写吗？

### ISSUE THREAD

**Issue by zzzzz-l-break** [codercup/unibest#42]
# Feature request（新功能建议）
如题

**Comment by ximo-156** [comment]
只要写成包的类型应该是支持的，用tsx语法记得导出组件来就可以

**Comment by codercup** [comment]
这个问题跟vue是否支持 tsx 是一个问题。支持的，vite.config.ts 里面引入 [@vitejs/plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx) 。

**Comment by 1473856015** [comment]
<img width="2560" height="1400" alt="Image" src="https://github.com/user-attachments/assets/f2cb7531-6812-465b-ab32-6e98616ff0c9" />
<img width="2560" height="1400" alt="Image" src="https://github.com/user-attachments/assets/8cd25362-9909-4d6d-9fe8-a6cc21962f0d" />

<img width="2560" height="1400" alt="Image" src="https://github.com/user-attachments/assets/12bdc2b6-5520-4343-87ba-95f67c007623" />
现在情况是，无论当组件引入，还是直接setup为jsx，都是报错，是有什么特殊配置项吗
