### ISSUE TITLE
vue版本问题，vue3.3.11，not vue 3.4

### ISSUE THREAD

**Issue by webarn** [codercup/unibest#44]
# 看到使用的vue版本是vue3.4 就兴冲冲的升级了，并使用了 `defineModel` 但是并未支持，报错。建议vue版本跟着官方走，官方现在使用的是vue3.3。 或者研究下如何可以在3.3中配置使用`defineModel`。辛苦了，点赞。非常完美

**Comment by codercup** [comment]
看来都是新特性爱好者，我也期待 defineModel 可以使用。是我最近升级误导你了，其实现在还是Vue3.3，让子弹飞一会儿吧

**Comment by codercup** [comment]
感谢，已经更新所有模板vue版本为 3.3.11
