### ISSUE TITLE
vscode 新建页面报错【最新版vscode+volar已经不会了】

### ISSUE THREAD

**Issue by wll8** [codercup/unibest#45]
# Bug report（问题描述）

创建 page 时报错 `找不到模块“@/utils”或其相应的类型声明` 。

![240402_130836](https://github.com/codercup/unibest/assets/28223260/b1503df0-4a5f-4693-9eca-ec1685918d02)

疑似自动导入功能相关问题。

## Steps to reproduce（问题复现步骤）

1. 已有的 login 目录打开 index.vue 不报错
2. 直接复制 login 目录，编辑器中存在文件 `/login copy/index.vue`
3. 打开 `/login copy/index.vue` 文件，报错找不到相关类型声明

重启 vscode 后可解决。但再创建一个页面时依然报错。

![71fbd6bdda04d075c8d1fe57b8cfbad](https://github.com/codercup/unibest/assets/28223260/a69faa0e-b046-4245-955a-a0d0b2824670)

![7623eca70169a64be26b97279f89989](https://github.com/codercup/unibest/assets/28223260/a76273da-3bdd-415f-9341-18262571a713)

## env (环境)

使用的当前仓库的 demo 分支 3bf4ea2f0da1886c49bc73966eb8648fc802a975 。

- node v18.19.0
- pnpm 8.12.1
- vscode 1.87.2
- os win10

**Comment by codercup** [comment]
跟群友聊过后，目前只能重启vscode:  ctrl + shift + P, 然后选择 restart
<img width="1043" alt="image" src="https://github.com/codercup/unibest/assets/65991901/9abb1787-a6e3-40a9-9ac7-02366adf78a3">

**Comment by codercup** [comment]
2024-04-24 最新版的vscode 已经不能复现了，不清楚是 vscode升级了，还是volar升级了。总之，现在随便新建都是OK的，没有任何报错。
