### ISSUE TITLE
有 tailwindcss 版本吗

### ISSUE THREAD

**Issue by tlerbao** [codercup/unibest#46]
请问有 tailwindcss 版本吗

XD 😰 实在无法理解国内盲目崇拜 antfu 的 unocss 是为何

**Comment by codercup** [comment]
你说说unocss哪里不满足你了~

**Comment by tlerbao** [comment]
1. 没有官方 Jetbrains 插件，我用 Webstorm 开发。
2. 最开始就用 Tailwind，习惯了，对于后出模仿它的 wind 和 uno 不感冒。4.0 更是让 unocss 尾灯都看不见。
3. 文档垃圾的一B，看看 Tailwind 的文档，每个样式都有可视化效果演示。
4. 群友反馈说不如 Tailwind。
<img width="342" alt="CleanShot 2024-04-03 at 11 48 27@2x" src="https://github.com/codercup/unibest/assets/20442232/5d5b34dc-7148-44a6-854d-fb5f38a3fbdd">

<img width="602" alt="CleanShot 2024-04-03 at 11 48 47@2x" src="https://github.com/codercup/unibest/assets/20442232/43073b9e-b901-4efa-a8ee-96f896c33535">
