### ISSUE TITLE
使用 Webstorm 打开项目，各种配置文件飘红问题

### ISSUE THREAD

**Issue by itxcr** [codercup/unibest#48]
# Bug report（问题描述）

使用webstorm打开，查看各配置文件，代码一直飘红

## Steps to reproduce（问题复现步骤）

1.项目install后使用webstorm打开，查看各配置文件时一直飘红，但是是可以追踪到该文件的，好奇是什么原因导致的
![image](https://github.com/codercup/unibest/assets/84362240/38ec3570-dba4-458a-ac78-e998ad8789d6)
2.查看 tsconfig.json, 里面的配置项为 "moduleResolution": "bundler"，经多方查找后发现是这个 "moduleResolution": "bundler", 导致的代码飘红，这个选项是 5.x 版本的 typescript 新增的功能，但是本项目中 typescript 用的是 v4.9.4，因此将 typescript 升级为 5.x 后，飘红问题解决
![image](https://github.com/codercup/unibest/assets/84362240/30fbc907-286d-4afb-a8ec-12f52e993949)
3.项目组可以根据需要衡量是否需要在主版本中升级 typescript 版本，本人暂时先升级使用。
以下是解决代码飘红问题后截图
![image](https://github.com/codercup/unibest/assets/84362240/213a22fc-1a20-4b50-979c-6d9376b68c86)
![image](https://github.com/codercup/unibest/assets/84362240/aa2c243b-5ae6-423a-9789-e91242c571dc)

**Comment by tlerbao** [comment]
是的昨天 install 发现各种波浪线，已经准备放弃换别的了，出去喝酒了，回来看你这帖子，看来还可以救一下

**Comment by codercup** [comment]
感谢，我一直以为我已经改为了 "moduleResolution": "Node", 这样是OK的。你居然还发现升级ts版本也可以解决，666。
因为我不用ws，所有我就按我知道的方式解决，就是  "moduleResolution": "Node"。已经推到所有的模板分支

**Comment by itxcr** [comment]
> 感谢，我一直以为我已经改为了 "moduleResolution": "Node", 这样是OK的。你居然还发现升级ts版本也可以解决，666。 因为我不用ws，所有我就按我知道的方式解决，就是 "moduleResolution": "Node"。已经推到所有的模板分支

互相学习，感觉你这个项目集成了我以前一直想做的一个模板，但是近两年的工作一直用不到 uni-app 也就没有继续玩了，但是前两天想做个自己的小程序，然后发现 uni-app 更新了好多东西，就寻思着找找现成的，感觉这个框架还有很多可以优化的点，后续有时间做完我的小程序后也加入到这个框架的改进中来，本想着用项目里面的 ”我的“ 页面，但是发现直接写那个路由会报错，等再细看看这个项目用的技术，可以一起改进改进

**Comment by codercup** [comment]
好的好的，相互学习。你说的”我的“页面会报错是啥意思啊？没懂。你先看看项目，如果后续还有问题，欢迎截图，贴代码啥的。
