### ISSUE TITLE
有钉钉小程序适配的方案计划吗

### ISSUE THREAD

**Issue by Kevin-Jii** [codercup/unibest#49]
# Feature request（新功能建议）

**Comment by codercup** [comment]
现在不能用吗？应该是可以的~如果运行报错，请看官网的”常见问题“章节。https://codercup.github.io/unibest-docs/reference/faq#_6-%E6%94%AF%E4%BB%98%E5%AE%9D%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%BF%90%E8%A1%8C%E6%8A%A5%E9%94%99%E3%80%82
