### ISSUE TITLE
路由守卫功能

### ISSUE THREAD

**Issue by luoqiz** [codercup/unibest#5]

**Comment by ymind** [comment]
期待！

**Comment by codercup** [comment]
方便描述一下使用场景吗？否则我不建议加这些功能

**Comment by ymind** [comment]
比如未登录的时候自动跳转到登录页，避免在每个page里面硬编码。

**Comment by codercup** [comment]
我是这么认为的，在h5页面用户可以随意进某个页面，是有这个需求的。

**Comment by codercup** [comment]
在非H5端，用户不能随意进某个页面。一般默认是进入首页的（或者部分可以分享的页面），这里又分2种情况：
1，首页（或者被分享的页面） 不需要登录，那就不需要拦截，在用户点击某个按钮或进入某个页面时需要登录再进行登录操作（在微信小程序的话，通常都是静默登录的）

**Comment by codercup** [comment]
最后，有没有比较好用路由拦截的第三方库，多列几个，我来研究下。（毕竟确实是会用得上）

**Comment by luoqiz** [comment]
免费版 uni-mini-router（我使用的）、uniapp-router-next，收费版 uni-simple-router 没用过，看文档功能很强

**Comment by codercup** [comment]
done
