### ISSUE TITLE
pnpm dev:app 报错

### ISSUE THREAD

**Issue by dingxiu8899** [codercup/unibest#53]
# Bug report（问题描述）

pnpm dev:app 报错

## System Info
使用的是vscode的base的模版

**Comment by codercup** [comment]
无图无真相，package.json 版本写下。

**Comment by codercup** [comment]
报错的截图也给一下

**Comment by SsyxSsyx** [comment]
1.使用 npx @dcloudio/uvm@latest 更新uni-app

**Comment by dingxiu8899** [comment]
添加了web3modal的包，按照官方示例，在h5能跑起来，但是pnpm dev:app就会报错
<img width="566" alt="截屏2024-04-17 21 01 12" src="https://github.com/codercup/unibest/assets/164471127/c4deb40a-a205-473d-bb92-a489eb3ca0d4">
Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.

**Comment by codercup** [comment]
uniapp 只有 h5 端支持web api, 其他端当然不行呀

**Comment by dingxiu8899** [comment]
感谢
