### ISSUE TITLE
手动新建页面文件，编译后route下自动生成分号导致编译失败，【插件问题】

### ISSUE THREAD

**Issue by JYS333** [codercup/unibest#58]
# Bug report（问题描述）
## Screenshot or Gif（截图或动态图）
![image](https://github.com/codercup/unibest/assets/29921357/91685403-db44-4dfc-9f7d-4cca26d49b3c)
![image](https://github.com/codercup/unibest/assets/29921357/5d28e206-5917-4635-8c47-43041c461f15)

如上图，当前vue文件为手动创建，代码由v3自动创建，修改页面代码后保存，会稳定产生额外`;`导致编译失败

## System Info

System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.79 GB / 15.67 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\nvm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Roaming\nvm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vue: ^3.4.21 => 3.4.21

**Comment by JYS333** [comment]
更正：是在保存文件时，在该位置自己生成一个分号，反复删掉，反复生成

**Comment by JYS333** [comment]
复现过程：
![image](https://github.com/codercup/unibest/assets/29921357/cf0e62b8-b303-4567-82f1-d4ef2646c7ee)

**Comment by codercup** [comment]
你检查一下你的插件，关于vue的，某个插件的问题。
