### ISSUE TITLE
在组件中使用enum枚举会报错：xxx is defined but never used. eslintno-unused-vars

### ISSUE THREAD

**Issue by dhanweb** [codercup/unibest#6]
解决方案之一是在`.eslintrc.cjs`中的`rules`字段添加 ` 'no-unused-vars': 'off', `
暂时未发现会影响其他功能

**Comment by codercup** [comment]
你这个配置也太暴力了吧，我后面看下。

**Comment by codercup** [comment]
方便截个图吗？我看看你怎么用的

**Comment by dhanweb** [comment]
图一是我的配置项，图二是加上去之后还是能够正确检测未使用的类型或者变量
原贴链接：https://stackoverflow.com/questions/57802057/eslint-configuring-no-unused-vars-for-typescript
![PixPin_2024-03-01_14-05-46](https://github.com/codercup/unibest/assets/105217481/f0d6ab7e-74f6-4657-81a3-7111e315e103)
![PixPin_2024-03-01_14-06-34](https://github.com/codercup/unibest/assets/105217481/9897b5b4-07f6-41c3-9934-103a67c90256)

**Comment by codercup** [comment]
`type test = {} ` 这个代码是在什么文件里面的?

**Comment by codercup** [comment]
要不你加群吧，在群里说比较方便

**Comment by codercup** [comment]
![image](https://github.com/codercup/unibest/assets/65991901/cffd97e1-1c00-4dc1-b5a8-bbea3a7ec52a)

**Comment by dhanweb** [comment]
> `type test = {} ` 这个代码是在什么文件里面的?

在.vue文件和.ts文件都会报这个错误的，加上我说的才能通过eslint校验

**Comment by codercup** [comment]
> > `type test = {} ` 这个代码是在什么文件里面的?
> 
> 在.vue文件和.ts文件都会报这个错误的，加上我说的才能通过eslint校验

因为你没使用啊。

**Comment by codercup** [comment]
![image](https://github.com/codercup/unibest/assets/65991901/3b4db774-6b66-4472-bb70-bcb0970156e3)
代码已经推了

**Comment by codercup** [comment]
fixed

**Comment by codercup** [comment]
fixed
