### ISSUE TITLE
开发app，每次保存后，都会白屏，必须重启应用。

### ISSUE THREAD

**Issue by Coding-Journey-Studio** [codercup/unibest#60]
# Bug report（问题描述）

开发app，每次保存后，都会白屏，必须重启应用。
因为用了插件，所以pages.json和那个manifest.js都是动态生成，无法直接再hbx里引入
而直接dev:app 每次修改都需要重启应用。

**Comment by codercup** [comment]
我mac电脑使用 ios 模拟器不会出现这个情况。windows 不清楚，而且有问题也超出了我的能力呀~

**Comment by Coding-Journey-Studio** [comment]
安卓模拟器确实会这样，就必须用hbx才可以。只能用hbx的base。但是好像你不咋更新hbx吧

**Comment by codercup** [comment]
> 安卓模拟器确实会这样，就必须用hbx才可以。只能用hbx的base。但是好像你不咋更新hbx吧

仓库地址在 [https://github.com/codercup/unibest-hbx](https://github.com/codercup/unibest-hbx)，你看看里面的issue 就懂了

**Comment by codercup** [comment]
> > 安卓模拟器确实会这样，就必须用hbx才可以。只能用hbx的base。但是好像你不咋更新hbx吧
> 
> 仓库地址在 https://github.com/codercup/unibest-hbx，你看看里面的issue 就懂了

工作太忙了，精力不足，hbx 项目大家自己维护，欢迎PR。如果想成为开发者，知会我一身，我邀请你~

**Comment by Coding-Journey-Studio** [comment]
🙏 了解了。
