### ISSUE TITLE
在微信小程序下，wd-swiper 不显示，且报错

### ISSUE THREAD

**Issue by likaia** [codercup/unibest#67]
在微信小程序下，wd-swiper 不显示，且报错：

Component is not found in path "node-modules/wot-design-uni/components/wd-swiper/wd-swiper" (using by "pages/index/index")(env: macOS,mp,1.06.2402040; lib: 3.4.1)

<img width="582" alt="image" src="https://github.com/codercup/unibest/assets/35120858/32cf6f15-2c9d-4fb8-86ab-d022f3980eea">

h5是可以的。
<img width="603" alt="image" src="https://github.com/codercup/unibest/assets/35120858/aeed387d-3dff-4744-95af-5414c0144958">

**Comment by codercup** [comment]
群里有说后续，通过重启解决了。尴尬~万能重启大法
