### ISSUE TITLE
添加迁移指南，比如把现有手机webapp转为这个项目的方法、实践

### ISSUE THREAD

**Issue by gaao** [codercup/unibest#68]
# Feature request（新功能建议）
有没有规划添加迁移指南，比如把现有手机webapp转为这个项目的方法、实践

**Comment by codercup** [comment]
你是说vue写的吗？API 和UI框架都要换啊，这个我只能提供思路。即使我有这样的项目，迁移成功了，也不一定适用你。
按照这个思路来就OK
