### ISSUE TITLE
编译到微信小程序源代码的压缩转译的代码对调试很不友好，请问这个需要怎么处理

### ISSUE THREAD

**Issue by moka-erb** [codercup/unibest#71]
# Bug report（问题描述）

please write your issue description here

## Screenshot or Gif（截图或动态图）
![image](https://github.com/codercup/unibest/assets/34873334/eda8327b-b09e-40db-a04e-607a6e87f7bf)

## System Info

`npx envinfo --system --npmPackages vue --binaries --browsers`

执行上面命令，将结果贴下面

**Comment by codercup** [comment]
可以自行开启的。如下图，或者看base模板代码，或者新建一个base模板项目。
![image](https://github.com/codercup/unibest/assets/65991901/c1dddb86-5d4b-444c-acc0-5e5bc5e55295)

**Comment by moka-erb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by codercup** [comment]
测试回复












飞鸽传书
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 下午5:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [codercup/unibest] 编译到微信小程序源代码的压缩转译的代码对调试很不友好，请问这个需要怎么处理 (Issue #71)




 这是来自QQ邮箱的假期自动回复邮件。
 &nbsp;
 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by codercup** [comment]
测试回复所有












飞鸽传书
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 下午5:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [codercup/unibest] 编译到微信小程序源代码的压缩转译的代码对调试很不友好，请问这个需要怎么处理 (Issue #71)




 这是来自QQ邮箱的假期自动回复邮件。
 &nbsp;
 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by moka-erb** [comment]
ok.多谢，找了一圈把这个漏掉了。。
