### ISSUE TITLE
使用 uv-parse 组件后报错 [unocss]​ ​failed to load icon "-"​

### ISSUE THREAD

**Issue by wll8** [codercup/unibest#77]
# Bug report（问题描述）

使用了此组件后，运行 `pnpm build:h5` 会出现 `[unocss]​ ​failed to load icon "-"​`

![image](https://github.com/codercup/unibest/assets/28223260/0ec3c5b0-489e-4784-81b0-f78b2b07e8a3)

## env (环境)

使用的当前仓库的 demo 分支 3bf4ea2f0da1886c49bc73966eb8648fc802a975 。

- node v18.19.0
- pnpm 8.12.1
- vscode 1.87.2
- os win10
- hbx  4.08
- @climblee/uv-ui 1.1.20

**Comment by codercup** [comment]
![image](https://github.com/codercup/unibest/assets/65991901/e555f73e-e7c7-4845-9da4-d8140bfc01b0)

没问题呀亲

**Comment by codercup** [comment]
已经推了，demo分支。

**Comment by wll8** [comment]
![image](https://github.com/codercup/unibest/assets/28223260/1f9354b8-82ca-4ba2-a19f-9e2230fb79dd)

- 用户使用的本来就是 vscode 的截图，提出问题说使用 vscode 试试
- 用户说的是 build:h5 说 dev:h5 没问题
- 没等用户继续反馈问题就 close 了问题

总结： 飞鸽牛逼！

**Comment by codercup** [comment]
![image](https://github.com/codercup/unibest/assets/65991901/ba42f8cc-c46e-47f4-86f8-ce9df7469c43)

线上也是正常的呀。（你说只是控制台报错吗？正常就行，哈哈，鸽鸽很忙的）

**Comment by codercup** [comment]
https://codercup.github.io/unibest/#/pages/demo/base/uv-ui

**Comment by codercup** [comment]
效果正常就行哈，这些小细节鸽鸽不理哈。
