### ISSUE TITLE
Base模板的layout功能貌似不生效

### ISSUE THREAD

**Issue by nrtzhou** [codercup/unibest#85]
所有的demo的模板是有效的，相关包降级后都不行

**Comment by Skiyee** [comment]
已修复，等待Review中

若着急使用的朋友，把 `@uni-helper/vite-plugin-uni-layouts` 依赖降至 `v0.1.7`

uni-helper/vite-plugin-uni-layouts#36

**Comment by nrtzhou** [comment]
谢谢，可以用了
