### ISSUE TITLE
HBuilderX启动报错

### ISSUE THREAD

**Issue by LeftProgrammer** [codercup/unibest#89]
# Bug report（问题描述）
通过HbuilderX第二次启动失败
18:39:29.003 项目 'app-base' 开始编译...
18:39:29.008 manifest.json中appid为空

## Steps to reproduce（问题复现步骤）

1. 根据使用文档安装依赖后，通过HbuilderX启动项目，第一次可以启动
2. 关掉进城，再次启动，无法启动，报错“manifest.json中appid为空”

## Screenshot or Gif（截图或动态图）
![image](https://github.com/codercup/unibest/assets/30935024/2100c9ac-3f43-4578-acd3-78fc1db6729f)

## System Info

`npx envinfo --system --npmPackages vue --binaries --browsers`

执行上面命令，将结果贴下面

**Comment by LeftProgrammer** [comment]
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
    Memory: 18.31 GB / 31.87 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vue: 3.4.21 => 3.4.21

**Comment by codercup** [comment]
appId 为空的问题，只需要”重新获取ID“ 就行了。
<img width="1312" alt="image" src="https://github.com/codercup/unibest/assets/65991901/30041b63-3c9c-4e53-b5cb-ed7dda713e8e">
另外，这个文档已经写了。在运行篇

**Comment by chergn** [comment]
![image](https://github.com/user-attachments/assets/b2621c20-5c4d-4eae-8257-eedbe27661ab)
