### ISSUE TITLE
新建的模版小程序端运行报错

### ISSUE THREAD

**Issue by 0131LWG** [codercup/unibest#96]
# Bug report（问题描述）

新建的模版允许 pnpm dev:mp-weixin 报错

## Steps to reproduce（问题复现步骤）
1. 运行pnpm create unibest test-unibest下载模版
2. pnpm i 安装依赖
3. 执行pnpm dev:mp-weixin，报错（H5 端正常运行）
4. 如果将引入组件注释正常运行

## Screenshot or Gif（截图或动态图）
![image](https://github.com/codercup/unibest/assets/30310735/faa006e7-af97-4157-a4e3-9fb507b77d9f)

## System Info
![image](https://github.com/codercup/unibest/assets/30310735/9490a92d-3840-4d76-a1bb-702e70eb88bf)

**Comment by codercup** [comment]
经过排查是因为我们有把pnpm-lock.yaml添加到版本管理，而uni-pages插件最新版本有问题。
<img width="668" alt="image" src="https://github.com/codercup/unibest/assets/65991901/d83a2f7f-edbb-4d2d-842e-d8baf22d7d8b">
0.2.20是好的，最新的0.2.25是有问题的。

**Comment by codercup** [comment]
目前已经把pnpm-lock.yaml加入版本管理，已经推送。最新的unibest版本是v2.4.0.
![Uploading image.png…]()

**Comment by chergn** [comment]
![image](https://github.com/user-attachments/assets/8a285600-9046-46f5-a7d2-2c0c6bcec958)
