### ISSUE TITLE
在js版本中uniapp打包为app一直处于40%

### ISSUE THREAD

**Issue by Luochao0511** [codercup/unibest#99]
我每个时间段的提交记录，都迁移分支跑项目，哎终于找到问题了，把我框红色标记的注释掉之后就不会出现uniapp打包app一直百分之40%了，这个问题困扰我属实太久了，终于解决了，想哭
![image](https://github.com/codercup/unibest/assets/93471473/3912995b-1e7b-4b56-8b7b-d3a022d4c0fb)

**Comment by codercup** [comment]
感谢。不过问下，你是啥电脑，windows 还是 mac.  看起来是用的 hbx 模板。我看看这个模板有没有更新，是不是已经解决这个问题了。

**Comment by codercup** [comment]
我看过了，已经解决了。（vite 升级到5.x后，不需要那段你注释的代码了，可以直接删除。）

**Comment by Luochao0511** [comment]
我用的js的版本，windows电脑
